name: Node.js CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Debug GitHub OIDC
        uses: github/actions-oidc-debugger@main
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571486265924:role/GitHubActions-ECR-CICD
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t cicd-node-backend .

      - name: Tag Docker image
        run: |
          docker tag cicd-node-backend:latest \
            571486265924.dkr.ecr.eu-north-1.amazonaws.com/cicd-node-backend:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
            571486265924.dkr.ecr.eu-north-1.amazonaws.com/cicd-node-backend:latest